/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.modelos;

/**
 *
 * @author ASUS
 */
public class PanelJuego extends javax.swing.JFrame {

    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 707));
        getContentPane().setLayout(null);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 20, 240, 150);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(720, 10, 150, 230);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 420, 150, 110);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 340, 220, 190);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/mapa0.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/mapa2.jpg"))); 
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 710);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/mapa0.jpg")));
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 710);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/mapa1.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 710);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/mapa0.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 710);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/mapa3.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 710);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/mapa0.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 710);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/mapa4.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 710);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/mapa0.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 760));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 710);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
